= eXtenderZ
François Lamboley <francois.lamboley@happn.com>

:happn: https://happn.com
:frizlab: https://github.com/Frizlab

image:https://img.shields.io/badge/platform-macOS%20|%20iOS%20|%20tvOS%20|%20watchOS-lightgrey.svg?style=flat[Platforms] link:https://swift.org/package-manager/[image:https://img.shields.io/badge/SPM-compatible-E05C43.svg?style=flat[SPM Compatible]] link:License.txt[image:https://img.shields.io/github/license/Frizlab/eXtenderZ.svg[License]] link:{happn}[image:https://img.shields.io/badge/from-happn-0087B4.svg?style=flat[happn]]

Use the full-extent of Objective-C’s runtime dynamicity.

== What is this?
This module allows changing the behavior of objects at runtime by creating custom classes on the fly and
 using `isa-swizzling` to change the class of the object instances whose behavior you want changed.

See https://frizlab.github.io/eXtenderZ/documentation/extenderz[the documentation] for more inforation.

== Installation
Even though there is no Package.swift file in this project in the main branch,
 the project is now SPM-compatible,
 with support for a dynamic and a static version of the package.

*⚠️ Important*: If you use the static version of the package, you *must* add the `-ObjC` flag in _Other Linker Flags_
 (`OTHER_LDFLAGS`) in the build settings of your project.

Compatibility with SPM is provided via an `xcframework` only.
Source SPM-compatibility cannot be provided AFAICT because the project has a part which does not use ARC, and has a custom modulemap.

Carthage installation should work too for the dynamic framework, but it hasn’t been tested.

== Versioning Note
The pbxproj sets `DYLIB_CURRENT_VERSION` and `DYLIB_COMPATIBILITY_VERSION` to `$(MARKETING_VERSION)`.
We set the same versions in both fields because this lib is not meant to be shared between processes, so we don’t really care about the versions.

== Notes About the Documentation
The doc compiler (`docc`) now supports Objective-C modules! \o/ ……… but it https://github.com/apple/swift-docc/issues/843[does not support extended Objective-C types].

To workaround this and avoid having all the main methods missing from the documentation, I did something terrible.
Basically, the methods that are defined in an extension of `NSObject` will be shown in `NSObject_WorkaroundForDoc` in the documentation.

See `NSObject_WorkaroundForDoc.h` for more information.

== Credits
This project was originally created by {frizlab}[François Lamboley] while working at {happn}[happn].
